name: Build & Unit Test

on:
  pull_request:
    branch:
        - 'main'
    paths:
      - ".github/**.md"
      - "README.md"
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit_test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Fail if draft
      if: github.event.pull_request.draft == true
      run:
        exit 1
    - name: Paas
      run: 'echo "No build required" '
