name: Build & Unit Test

on:
  pull_request:
    branch:
      - 'main'
    paths-ignore:
      - ".github/**.md"
      - "README.md"
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
        torch: [1.8.0, 1.9.0]
        mmcv: [1.7.0]
        include:
          - torch: 1.8.0
            torchvision: 0.9.0
          - torch: 1.9.0
            torchvision: 0.10.0

    steps:
      - name: Fail if draft
        if: github.event.pull_request.draft == true
        run: |
          exit 1
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install PyTorch
        run: pip install torch==${{matrix.torch}}+cpu torchvision==${{matrix.torchvision}}+cpu -f https://download.pytorch.org/whl/torch_stable.html
      - name: Install OpenMMLab packages
        run: |
          pip install openmim
          mim install mmcv-full==${{ matrix.mmcv }}
          mim install 'mmcls<1.0.0rc0' 'mmdet<3.0.0rc0' 'mmsegmentation<1.0.0rc0' 'mmedit<1.0.0rc0'
      - name: Install SIATune
        run: |
          pip install -e ".[optional]"
      - name: Run unittests and generate coverage report
        run: |
          pip install pytest coverage
          coverage run --branch --source siatune -m pytest tests/
          coverage xml
          coverage report -m
      - name: Display coverage
        uses: codecov/codecov-action@v3
        with:
          file: coverage.xml
          flags: unittests
