name: Build & Push Docker Image
on:
  push:
    branches:
      - 'main'
      - 'test/*'
    tags:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKERFILE_PATH: "./docker/Dockerfile"
  PROJECT_NAME: "mlops"
  APP_NAME: "siatune"

jobs:
  build:
    runs-on: ["self-hosted", "linux", "docker", "ubuntu20.04"]
    timeout-minutes: 120
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        # submodules: true
    - name: login container registry
      uses: docker/login-action@v1.12.0
      with:
        registry: ${{ secrets.CONTAINER_REGISTRY_URL }}
        username: ${{ secrets.CONTAINER_REGISTRY_ID }}
        password: ${{ secrets.CONTAINER_REGISTRY_PW }}
    - name: set tag
      run: |
        if ${{ github.event_name == 'pull_request' }}; then
          echo CONTAINER_TAG=pr-${{github.head_ref}}-$(date +%Y%m%d).${{github.run_number}} | sed -e "s/\//\-/g" >> $GITHUB_ENV
        else
          echo CONTAINER_TAG=${{github.ref_name}}-$(date +%Y%m%d).${{github.run_number}} | sed -e "s/\//-/g" >> $GITHUB_ENV
        fi
    - name: dump version
      run: |
        echo "" >> ${{ env.DOCKERFILE_PATH }}
        echo "ENV GIT_COMMIT_ID=${{ github.sha }} \\" >> ${{ env.DOCKERFILE_PATH }}
        echo "   BUILD_DATE=$(date +%Y.%m.%d) \\" >> ${{ env.DOCKERFILE_PATH }}
        echo "   VERSION=${{ env.CONTAINER_TAG }}" >> ${{ env.DOCKERFILE_PATH }}
        echo "ENV GIT_COMMIT_ID {{ github.sha }}"
        echo "ENV BUILD_DATE $(date +%Y.%m.%d)"
        echo "ENV VERSION ${{ env.CONTAINER_TAG }}"
    - name: build the docker image
      run: |
        docker build . --file ${{ env.DOCKERFILE_PATH }} --tag ${{ secrets.CONTAINER_REGISTRY_URL }}/${{ env.PROJECT_NAME }}/${{ env.APP_NAME }}:${{ env.CONTAINER_TAG }}
    - name: push the docker image
      run: docker push ${{ secrets.CONTAINER_REGISTRY_URL }}/${{ env.PROJECT_NAME }}/${{ env.APP_NAME }}:${{ env.CONTAINER_TAG }}
