name: Build & Unit Test

on:
  pull_request:
    branch:
        - 'main'
    paths-ignore:
      - ".github/**.md"
      - "README.md"


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit_test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    timeout-minutes: 120

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Build and install
      run: |
          pip install torch==1.9.1+cu111 torchvision==0.10.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html
          pip install mmcv-full==1.4.7 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html
          pip install gpytorch==0.3.6 nevergrad mmcls mmdet mmsegmentation protobuf==3.20
          pip install -e ".[optional]"
    - name: Run unittests and generate coverage report
      run: |
          pip install pytest coverage
          coverage run --branch --source siatune -m pytest tests/
          coverage xml
          coverage report -m
    - name: Display coverage
      uses: codecov/codecov-action@v3
      with:
        file: coverage.xml
        flags: unittests
