name: Build & Unit Test

on:
  pull_request:
    branch:
        - 'main'
    paths:
      - ".github/**.md"
      - "README.md"
    types: [ready_for_review]


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit_test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
     - run: 'echo "No build required" '
