name: Build & Unit Test

on:
  pull_request:
    branch:
        - 'master'
    paths-ignore:
      - ".github/**.md"
      - "README.md"


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit_test:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Build and install
      run: |
          pip install torch==1.9.1+cu111 torchvision==0.10.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html
          pip install mmcv-full==1.4.7 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html
          pip install nevergrad mmdetection mmsegmentation
          pip install -e .
    - name: Run unittests and generate coverage report
      run: |
          pip3 install pytest coverage
          coverage run --branch --source mmtune -m pytest tests/
          coverage xml
          coverage report -m
    - name: Display coverage
      uses: ewjoachim/coverage-comment-action@v1
      with:
        GITHUB_TOKEN: ${{ github.token }}
