name: Build & Unit Test

on:
  pull_request:
    branch:
        - 'main'
    paths-ignore:
      - ".github/**.md"
      - "README.md"
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit_test:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Fail if draft
      if: github.event.pull_request.draft == true
      run:
        exit 1

    - name: checkout
      uses: actions/checkout@v2

    - name: Build and install
      run: |
          pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
          pip install openmim
          mim install mmcv-full
          mim install mmcls mmdet mmsegmentation
          pip install gpytorch==0.3.6 nevergrad protobuf==3.20
          pip install -e ".[optional]"
    - name: Run unittests and generate coverage report
      run: |
          pip install pytest coverage
          coverage run --branch --source siatune -m pytest tests/
          coverage xml
          coverage report -m
    - name: Display coverage
      uses: codecov/codecov-action@v3
      with:
        file: coverage.xml
        flags: unittests
